### ISSUE TITLE
Sensitivity of texmex to threshold value

### ISSUE THREAD

**Issue by jbauder** [harrysouthworth/texmex#15]
Hello,
I have been attempting to model some data I have with a generalized Pareto distribution using the evm function in texmex. These data are measures of probability density values extracted from a kernel density surface representing animal home ranges. As a result there are many zeros in the data. I would like to use these zeros to model the GPD because they represent important biological information about animal home ranges. 

![all snakes pif](https://cloud.githubusercontent.com/assets/6606040/6972766/ef4bb7f4-d953-11e4-9af1-ad0ca3e4ad3b.jpeg)

I also have several binary categorical covariates I am using to model shape and scale. However, when I set threshold equal to zero these zeros are not included in the fit of the GPD. Does anyone have any recommendations about how to include these zeros? I have tried setting threshold equal to small negative values but got the following error messages:

Error in solve.default(family$info(o)) : 
  system is computationally singular: reciprocal condition number = 4.94239e-32
In addition: Warning message:
In family$info(o) : Fitted values of xi < -0.5

I have also tried multiplying/adding arbitrary positive constants to my data to change the range of my distribution (but not its shape) to allow the GPD model to converge. For example, if I multiply each data point by 1,000,000 and then add 1 (so there are no zeros in the data) I get GPD parameter estimates that provide a nice fit to my data. But I am concerned about the arbitrariness of selecting the constants. As far as I can tell the value of the constant doesn't matter as long as I am consistent in applying the constant.
Any suggestions would be greatly appreciated.

thanks,
Javan Bauder

**Comment by janetheffernan** [comment]
Hi JavanThanks for your enquiry - it's always interesting to see how people are using our package.The GPD's strength as a model derives from its theoretical motivation as the limiting distribution for threshold excesses of continuous variables, provided the threshold  is chosen sufficiently high. This leads me to ask a few questions of you and your application:First, why are you using the GPD? You do not mention any extreme value aspect of your application.  Are you modelling threshold excesses? Have you looked at a range of thresholds to ensure your threshold is high enough for the limit theory to be likely to hold?Second: since the motivation for the GPD assumed your variable to derive from an underlying continuous distribution, why do you expect it to accommodate a large number of ties which you have in your data? A continuous underlying dist would preclude *any* ties so I would not expect the fit to be good to data with many ties at the threshold.I agree that adding to or multiplying  ‎your data, using arbitrary constants is not a satisfactory way to proceed. Instead, I would suggest using a combination of distributions: perhaps a mixture dist with point mass at zero and GPD above zero, or use an even higher threshold with some other dist below that thresh (simplest would be the empirical dist below the thresh - this is a common approach which should work well if you have lots fo data) and the GPD above. If you don't particularly have an extreme value motivation for your problem, then you could consider different flexible families of parametric distributions perhaps  a zero inflated Gamma, or weibull.                                                                                                                                     I hope these thoughts are helpful to you and your workBest wishesJan                                                                                                                                                                                                                                                                                                                                                                                                                   From: jbauderSent: Thursday, 2 April 2015 21:22To: harrysouthworth/texmexReply To: harrysouthworth/texmexSubject: [texmex] Sensitivity of texmex to threshold value (#15)Hello,
I have been attempting to model some data I have with a generalized Pareto distribution using the evm function in texmex. These data are measures of probability density values extracted from a kernel density surface representing animal home ranges. As a result there are many zeros in the data. I would like to use these zeros to model the GPD because they represent important biological information about animal home ranges. 



I also have several binary categorical covariates I am using to model shape and scale. However, when I set threshold equal to zero these zeros are not included in the fit of the GPD. Does anyone have any recommendations about how to include these zeros? I have tried setting threshold equal to small negative values but got the following error messages:

Error in solve.default(family$info(o)) : 
  system is computationally singular: reciprocal condition number = 4.94239e-32
In addition: Warning message:
In family$info(o) : Fitted values of xi < -0.5

I have also tried multiplying/adding arbitrary positive constants to my data to change the range of my distribution (but not its shape) to allow the GPD model to converge. For example, if I multiply each data point by 1,000,000 and then add 1 (so there are no zeros in the data) I get GPD parameter estimates that provide a nice fit to my data. But I am concerned about the arbitrariness of selecting the constants. As far as I can tell the value of the constant doesn't matter as long as I am consistent in applying the constant.
Any suggestions would be greatly appreciated.

thanks,
Javan Bauder

—Reply to this email directly or view it on GitHub.

**Comment by jbauder** [comment]
Hi Dr. Heffernan,
Thanks for your quick reply. I really am only using a GPD to model data with a large number of very small values and extreme right skew and do not have any reason to model extreme values in my data any differently than the "non-extreme" values. So in that sense any continuous distribution that can accommodate my data would suit my purposes. I will certainly try some of the other distributions you have suggested. As I have little experience with distributions such as the gamma and Weibull, do you know of any packages that can fit those distributions and model their parameters as a function of covariates? I am also not familiar with using a point-mass at zero and a GPD above zero. Is this something that can be accomplished in texmex? Any suggestions about how to pursue such an option would be greatly appreciated.
Thank you again,
Javan

**Comment by janetheffernan** [comment]
HiI'm not sure of the best way to fit these but you could try asking your question on‎http://stackoverflow.com/questions/tagged/rwhere it would reach a wider audience of expertiseGood luck with your research!Best wishesJan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: jbauderSent: Friday, 3 April 2015 14:44To: harrysouthworth/texmexReply To: harrysouthworth/texmexCc: Janet HeffernanSubject: Re: [texmex] Sensitivity of texmex to threshold value (#15)Hi Dr. Heffernan,
Thanks for your quick reply. I really am only using a GPD to model data with a large number of very small values and extreme right skew and do not have any reason to model extreme values in my data any differently than the "non-extreme" values. So in that sense any continuous distribution that can accommodate my data would suit my purposes. I will certainly try some of the other distributions you have suggested. As I have little experience with distributions such as the gamma and Weibull, do you know of any packages that can fit those distributions and model their parameters as a function of covariates? I am also not familiar with using a point-mass at zero and a GPD above zero. Is this something that can be accomplished in texmex? Any suggestions about how to pursue such an option would be greatly appreciated.
Thank you again,
Javan

—Reply to this email directly or view it on GitHub.
